# This is a config for E2B sandbox template.
# You can use template ID (qmgtqx9tiv2ljn3ywbu3) or template name (s3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("s3") # Sync sandbox
# sandbox = await AsyncSandbox.create("s3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('s3')

team_id = "f32d0ddf-60c2-400c-b77c-22161b928db9"
dockerfile = "e2b.Dockerfile"
template_name = "s3"
template_id = "qmgtqx9tiv2ljn3ywbu3"
