# This is a config for E2B sandbox template.
# You can use template ID (16kpb03xoz989hqoehp6) or template name (v6969b) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v6969b") # Sync sandbox
# sandbox = await AsyncSandbox.create("v6969b") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v6969b')

team_id = "944314e0-c304-427a-bbe7-c0bbb6bcd5cd"
start_cmd = "/bin/bash /compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v6969b"
template_id = "16kpb03xoz989hqoehp6"
